### ISSUE TITLE
Nut Vote

### ISSUE THREAD

**Issue by FauconFan** [Heijix/Warehouse#1]
Here is the issue to vote of the creation of the Nut Project.

[Link Documentation](https://github.com/Heijix/Warehouse/tree/master/IdeaBox/Nut)

1/3.

EDIT:

0/3. There is a conception problem. Have to work on it...

EDIT EDIT:

That was a stupid problem. Resolved in the question if we write the question properly
1/3

**Comment by xavitator** [comment]
2/3 for me ;)

**Comment by elusyo** [comment]
And finally he does it ! I give the last vote 3/3
**Project is launched** :+1:

**Comment by FauconFan** [comment]
And it does it. When i have to go to see the match. Well done x)

I'll create the project and the participation file, when i got a second, tomorrow though.

Closing this when i'll create the repo. And closing all existing issue from rhis issue, and create the same on the new repo.

**Comment by FauconFan** [comment]
https://github.com/Heijix/nut-lang/
