### ISSUE TITLE
Eos

### ISSUE THREAD

**Issue by elusyo** [Heijix/Warehouse#11]
I've created a Readme file to talk about the project. Tell me what you think about it. It isn't a for now project but something to improve, write, etc when we have time!

**Comment by FauconFan** [comment]
It's not very clear to me. what is exactly a EOS file. And you may have to use the ``` notation to write code

```ocaml
let main () = print_endline "Hello world !"
```

The file is too miscellaneous...

You use sh eos.sh. I thought that was a ocaml project.

**Comment by elusyo** [comment]
There was a mistake in my readme file. Now it's easier to read!
Eos file is a configuration file, most likely write in nut, with information to put in headers.

**Comment by FauconFan** [comment]
eos.nut ? x)

**Comment by FauconFan** [comment]
Ok, some questions about it :
 - What are the options in oes file ? Be more explicit, just name and organisation is poor.
 - We have to find a way to represent a template for headers. Maybe we can adopt the way of zsh, we just have a bench of templates hardcoded in eos, then we just put the name of the header template in eos.
 - do you want to deploy eos, with opam later ?
 - can i have a kiss next time ? :+1:

**Comment by elusyo** [comment]
The Readme is a just a base to define how we can use it.
 * Sure I will add it! If you have options that seem useful, you can add them directly in the file.
 * What do you mean by templates in headers?
* Of course! It's easier to install :+1: 
* You don't have to ask for this :kissing:

**Comment by FauconFan** [comment]
- Like creation date, modification date, last user modifier, user who created etc...
 - examples of templates :
```ocaml
(* ************************************************************************** *)
(*                                                                            *)
(*                                                        :::      ::::::::   *)
(*   {{NAME}}                                           :+:      :+:    :+:   *)
(*                                                    +:+ +:+         +:+     *)
(*   By: {{USER}} <{{MAIL}}>                        +#+  +:+       +#+        *)
(*                                                +#+#+#+#+#+   +#+           *)
(*   Created: {{DATE}} by {{USER}}                     #+#    #+#             *)
(*   Updated: {{DATE}} by {{USER}}                    ###   ########.fr       *)
(*                                                                            *)
(* ************************************************************************** *)
```

This is the official template header of 42 for ocaml. This is a example. But we may have to hardcode a template depending of the form. and we will have an option in eos, Like in zsh, we will use themes for headers (agaster etc).
 - :+1: 
- God damn YES

**Comment by elusyo** [comment]
* The problem is if you have templates how can you change informations into? This is a good idea, but we must have maybe two options. One with no template and the other with templates.
