### ISSUE TITLE
Root object and named object

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#2]
## Question :
Could you precise what is the difference between root object and named object ?

## Details :
Can we compare a root object to an anonymous object in Java ? 
How can we use, or call, a root object ? 
Do you need determine all specifications when we call the object ?

You specify it in the [exemple page](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Examples.md), however it is not clear for me...

**Comment by FauconFan** [comment]
I give a more detailed explanation

[Link Commit](https://github.com/Heijix/Warehouse/commit/b89e6d61664a439e005cf16321c02cbd2034f48e)

If it's okay for you now, you can close this issue. :+1:
