### ISSUE TITLE
B4 error

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#3]
I based my issue on this [page](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Implementation.md#errors-code-and-meaning) and on the error subsection.

Could B4 error be just a warning and not an error ?
We can read a .nut document whereas it contains an unused alias... Moreover, if we want to verify a file for import (with no basic data), it will return an error and also stop the verification.

**Comment by FauconFan** [comment]
Good idea, i have thought about this. But i thought that it will cause more problem than solutions. But that was stupid.

9eecf3eb48c20f224e467b40ce96495460c9ce58

It gave me an idea, ^^

Letting you closing the issue
