### ISSUE TITLE
Common grammar

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#4]
I have two comments for the [common grammar](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Grammar.md#common-grammar) : 

1. The "String" state can be just : 

```
string
    " chars_d "
    ' chars_s '
```
Because ```chars_d``` and ```chars_s``` contain ```None```.

2. @elusyo and I found a shortcut for ignored characters and commented lines : 

```
commentaire = "#"[^\n\r]*
```

**Comment by elusyo** [comment]
Comment trick works for inline and blocks comments

**Comment by xavitator** [comment]
The original comment trick, in Java, is :
```
commentaire = ("/*"[^]*"*/") | ("//"[^\n\r]*)
```
