### ISSUE TITLE
Local and remote import

### ISSUE THREAD

**Issue by xavitator** [Heijix/Warehouse#7]
Link of [import description](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Language.md#local-and-remote-imports).

It is writting that imported files must only contain others imports and Data definitions, but not data itself. 

Maybe imported files can contain data. However if there is an overwriting of a Data definition or of a basic data, it throws an exception (error).

**Comment by FauconFan** [comment]
I don't understand this issue... ^^

Maybe you are talking about the C5 error. [See link](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Implementation.md#consistency-analysis-c)

**Comment by xavitator** [comment]
In the [langage document](https://github.com/Heijix/Warehouse/blob/master/IdeaBox/Nut/Language.md#local-and-remote-imports), you deal with the fact that an imported file cannot contain this (it throws an error) : 
```
&[R123] Color {
    red: 255
    green: 42
    blue: 57
}

@ Picture {
    name: "Awesome picture"
    dateCreation: 1530264298
    dateModification: 1530264399
    image: Image {
        size_x: 1
        size_y: 2
        content: [
            *[R123]
            *[R123]
        ]
    }
}
```
because it is a data and not a data definition like tou said, no ?
if I understand what you said.

**Comment by FauconFan** [comment]
Aliases objects is now allowed in imported objects. Root objects are no allowed. I had a new dev definition then we can understand each other. OI for Only-Importable and OR for Only-Readable. Then we can distinguish OI file and OR file. The difference is that OI file cannot define any root file with '@' character, and OR file can (and have to).

b89391a5441ff22fb113e167028a46e7658b397d

Good issue, dude

**Comment by xavitator** [comment]
Is it a file extension? Like a .oi and .or?

**Comment by FauconFan** [comment]
No, it's just about qualifiers. For us, the user doesn't have to see the difference. It's when we are parsing the language is we know if it's a OI or OR file. It is like internal vocabulary. The .nut file is the only file extension...

**Comment by xavitator** [comment]
Maybe it could be a great idea to have a different extension between OI filed and OR files, like in ocaml where some type of file have different extensions?

**Comment by FauconFan** [comment]
It is not an extension. It is just about handling error inside the library. It is not a file extension. It is just an internal qualifier. It is just terminology for explanation.

**Comment by xavitator** [comment]
Yes, I understood, I just propose a different extension between OI files and OR files.

**Comment by FauconFan** [comment]
I dont think it's relevant... Maybe as à indication. But it does have to be necessary. Personnally, I will never do that I think...
